config/routes.rb
Rails.application.routes.draw do
  root 'tweets#new'
  resources :tweets, only: [:new, :create] do
    collection do
      get 'post'
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  # mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :twitter_client, except: :new
  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(create_params)
    redirect_to :root
  end

  def post
    tweet = Tweet.order('rand()').first
    status = tweet.text
    media = open(tweet.image)
    @client.update_with_media(status, media)
    redirect_to :root
  end

 def twitter_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = Settings.twitter[:consumer_key]
      config.consumer_secret = Settings.twitter[:consumer_secret]
      config.access_token = Settings.twitter[:access_token]
      config.access_token_secret = Settings.twitter[:access_token_secret]
    end
  end

  def image_template
    if self.class == String
      tf = Tempfile.new
      tf.print(file_data.read)
      tf.rewind
    else
      return self
    end
      # ext = File.extname(url)
      # name = File.basename(url, ext)
      # Tempfile.new([name, ext])
  end

  private
  def create_params
    params.require(:tweet).permit(:text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>画像付きツイートbot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
  <%= f.text_area :text, cols: 40, rows: 5 ,maxlength: 140, placeholder: "ツイートメッセージ" %>
  <%= f.text_field :image %>
  <%= f.submit '保存' %>
<% end %>
<hr>
  <button type="submit" style = "width: 70px; height: 25px;"><%= link_to 'ツイート', post_tweets_path %></button>